### PR TITLE
Initial NetBox v3.3 support

### PR DESCRIPTION
**Pull request by hpreston**
Here is my initial approach to updating the plugin to support NetBox v3.3.  The work all revolves around the changes to the Cable / CableTermination models for data.  

I went with an approach that would leave the yaml format for the initializer files the same, and allow import to v3.3 without errors.  

I still need to run through the doc updates for the plugin, but I wanted to get feedback on the way I updated the code logic before getting too far along.

### CODE REVIEW

**Comment by hpreston** [comment]
This branch builds on the changes from the updates to the v3.2 version I had made and that has already been merged in.  However diffs seem to be comparing to the main branch before !18.

**Comment by tobiasge** [comment]
> This branch builds on the changes from the updates to the v3.2 version I had made and that has already been merged in. However diffs seem to be comparing to the main branch before !18.

I think the problem is that I squashed and merged the previous PR. You would probably need to create a new branch based on main and cherry-pick the cable related commits into that new branch. A force push to this PR should then resolve the problem.

**Comment by hpreston** [comment]
The tests are failing with cables for Circuits.  The data we use in our system doesn't include circuits so I didn't catch this issue.  I'm updating my testing to check with the same initialization data used in the plugin tests and will verify all types of cable work with v3.3 with additional updates to the PR.

**Comment by hpreston** [comment]
Alright, I've got all the tests passing now for the v3.3 version of NetBox and initializers.  I still need to complete the documentation updates relevant to this change.  That should be one more push into the branch and PR and it'll be ready to go.

**Pull request merged**
